[package]
name = "kp-runtime-api"
version = "2.0.0"
authors = ["ctt-dev"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false }
frame-support = { version = '2.0.0', default-features = false, path = "../../../../../frame/support" }
sp-api = { version = '2.0.0', default-features = false, path = "../../../../../primitives/api" }
sp-std = { version = '2.0.0', default-features = false, path = "../../../../../primitives/std" }
sp-runtime = { version = '2.0.0', default-features = false, path = "../../../../../primitives/runtime" }
sp-core = { version = '2.0.0', default-features = false, path = "../../../../../primitives/core" }
primitives = { package = "ctt-primitives", path = "../../../primitives", default-features = false }
kp = { version = "2.0.0", path = "../../kp", package = "ctt-pallet-kp", default-features = false }

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
    'frame-support/std',
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
]
